baseURL = "https://qaul.net/"
title = "qaul – قول"
theme = "hugo-theme-qaul"
DefaultContentLanguage = "en"


[params]
  description = "Internet independent wireless mesh communication app"
  images = ["img/qaul-splash.jpg"]


[languages]
  [languages.en]
    weight = 1
    LanguageName = "English"
  [languages.de]
    weight = 3
    LanguageName = "Deutsch"
  [languages.ar]
    weight = 2
    LanguageName = "العربية"


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
